Vagrant.configure("2") do |config|
    # The Packer box we just added
    config.vm.box = "kafl_windows"
      # our box name in libvirt
    config.vm.define "vagrant-kafl-windows"
  
    config.vm.synced_folder "sharedir", '/vagrant', type: 'rsync'
    config.vm.provider :libvirt do |libvirt|
        libvirt.cpus = 4
        libvirt.memory = 4096
      end
  end
  