- name: Deploy
  hosts: default
  vars:
    cmd_path: "{{ ansible_env['SystemRoot'] }}\\System32\\cmd.exe"
    iexplore_path: "{{ ansible_env['ProgramFiles(x86)'] }}\\Internet Explorer\\iexplore.exe"
    string_with_spaces: "A String With Spaces"
  tasks:
    - name: test one ansible.windows.quote
      win_shell: "{{ iexplore_path | ansible.windows.quote }} /?"
      args:
        executable: cmd
      register: result
      failed_when:
        - result.rc != 0
        - result.rc != 1
      
    - name: test two ansible.windows.quote
      win_shell: "{{ iexplore_path | ansible.windows.quote }} {{ iexplore_path | ansible.windows.quote }}"
      args:
        executable: cmd
