- name: Deploy
  hosts: default
  tasks:
    - name: execute win_shell free form
      win_shell: |
        echo 'First line'
        echo 'Second line'
        echo 'Third line'
      args:
        executable: cmd
      register: output

    - name:
      debug:
        var: output.stdout_lines
